//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBaseVue_Models.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Order.
        /// </summary>
        public static string ACCEPT_ORDER {
            get {
                return ResourceManager.GetString("ACCEPT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string ACCEPTED {
            get {
                return ResourceManager.GetString("ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Shipment.
        /// </summary>
        public static string ADD_TO_SHIPMENT {
            get {
                return ResourceManager.GetString("ADD_TO_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string APPOINTMENT {
            get {
                return ResourceManager.GetString("APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Approval Date.
        /// </summary>
        public static string APPOINTMENT_APPROVAL_DATE {
            get {
                return ResourceManager.GetString("APPOINTMENT_APPROVAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string APPOINTMENT_DATE {
            get {
                return ResourceManager.GetString("APPOINTMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Status.
        /// </summary>
        public static string APPOINTMENT_STATUS {
            get {
                return ResourceManager.GetString("APPOINTMENT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time.
        /// </summary>
        public static string APPOINTMENT_TIME {
            get {
                return ResourceManager.GetString("APPOINTMENT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Matrix.
        /// </summary>
        public static string APPROVAL_MATRIX {
            get {
                return ResourceManager.GetString("APPROVAL_MATRIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Driver&amp;Truck.
        /// </summary>
        public static string ASSIGN_DRIVER {
            get {
                return ResourceManager.GetString("ASSIGN_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Qty.
        /// </summary>
        public static string ASSIGN_QTY {
            get {
                return ResourceManager.GetString("ASSIGN_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string ASSIGN_REASON {
            get {
                return ResourceManager.GetString("ASSIGN_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ASSIGN_REASON_OTHERS {
            get {
                return ResourceManager.GetString("ASSIGN_REASON_OTHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Transporter.
        /// </summary>
        public static string ASSIGN_TRANSPORTER {
            get {
                return ResourceManager.GetString("ASSIGN_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to Transporter.
        /// </summary>
        public static string ASSIGNED_TO_TRANSPORTER {
            get {
                return ResourceManager.GetString("ASSIGNED_TO_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reject Date.
        /// </summary>
        public static string AUTO_REJECT_DATE {
            get {
                return ResourceManager.GetString("AUTO_REJECT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string BUSINESS_SEGMENT {
            get {
                return ResourceManager.GetString("BUSINESS_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Shipment.
        /// </summary>
        public static string CANCEL_SHIPMENT {
            get {
                return ResourceManager.GetString("CANCEL_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge OA Company.
        /// </summary>
        public static string CHARGE_OA_COMPANY {
            get {
                return ResourceManager.GetString("CHARGE_OA_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collective LN.
        /// </summary>
        public static string COLLECTIVE_LN {
            get {
                return ResourceManager.GetString("COLLECTIVE_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete order.
        /// </summary>
        public static string COMPLETE_ORDER {
            get {
                return ResourceManager.GetString("COMPLETE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        public static string COMPLETED_DATE {
            get {
                return ResourceManager.GetString("COMPLETED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string CONVERTED {
            get {
                return ResourceManager.GetString("CONVERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Order.
        /// </summary>
        public static string COPY_ORDER {
            get {
                return ResourceManager.GetString("COPY_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Appointment.
        /// </summary>
        public static string CREATE_APPOINTMENT {
            get {
                return ResourceManager.GetString("CREATE_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CREATED_DATE {
            get {
                return ResourceManager.GetString("CREATED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer/Vendor.
        /// </summary>
        public static string CUSTOMER_VENDOR {
            get {
                return ResourceManager.GetString("CUSTOMER_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CUSTOMER_VENDOR_ADDRESS {
            get {
                return ResourceManager.GetString("CUSTOMER_VENDOR_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted By.
        /// </summary>
        public static string DELETED_BY {
            get {
                return ResourceManager.GetString("DELETED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Date.
        /// </summary>
        public static string DELETED_DATE {
            get {
                return ResourceManager.GetString("DELETED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DELIVERY_ADDRESS {
            get {
                return ResourceManager.GetString("DELIVERY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order No.
        /// </summary>
        public static string DELIVERY_ORDER_NO {
            get {
                return ResourceManager.GetString("DELIVERY_ORDER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Qty.
        /// </summary>
        public static string DELIVERY_QTY {
            get {
                return ResourceManager.GetString("DELIVERY_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery UOM.
        /// </summary>
        public static string DELIVERY_UOM {
            get {
                return ResourceManager.GetString("DELIVERY_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DESTINATION {
            get {
                return ResourceManager.GetString("DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string DISTRIBUTION {
            get {
                return ResourceManager.GetString("DISTRIBUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Date.
        /// </summary>
        public static string DOC_DATE {
            get {
                return ResourceManager.GetString("DOC_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. No.
        /// </summary>
        public static string DOC_NO {
            get {
                return ResourceManager.GetString("DOC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Type.
        /// </summary>
        public static string DOC_TYPE {
            get {
                return ResourceManager.GetString("DOC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string DRIVER {
            get {
                return ResourceManager.GetString("DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Appointment.
        /// </summary>
        public static string EDIT_APPOINTMENT {
            get {
                return ResourceManager.GetString("EDIT_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Order.
        /// </summary>
        public static string EDIT_ORDER {
            get {
                return ResourceManager.GetString("EDIT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shipment.
        /// </summary>
        public static string EDIT_SHIPMENT {
            get {
                return ResourceManager.GetString("EDIT_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited By.
        /// </summary>
        public static string EDITED_BY {
            get {
                return ResourceManager.GetString("EDITED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Date.
        /// </summary>
        public static string EDITED_DATE {
            get {
                return ResourceManager.GetString("EDITED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estate.
        /// </summary>
        public static string ESTATE {
            get {
                return ResourceManager.GetString("ESTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string FACTORY {
            get {
                return ResourceManager.GetString("FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FORM_MODE_CREATE {
            get {
                return ResourceManager.GetString("FORM_MODE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to Transporter.
        /// </summary>
        public static string FORM_MODE_DISPATCH {
            get {
                return ResourceManager.GetString("FORM_MODE_DISPATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per / UOM.
        /// </summary>
        public static string FREIGHT_APPROVAL_PER_UOM {
            get {
                return ResourceManager.GetString("FREIGHT_APPROVAL_PER_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Biaya Best Price.
        /// </summary>
        public static string FREIGHT_BEST_PRICE {
            get {
                return ResourceManager.GetString("FREIGHT_BEST_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Price/UOM.
        /// </summary>
        public static string FREIGHT_BEST_PRICE_PER_UOM {
            get {
                return ResourceManager.GetString("FREIGHT_BEST_PRICE_PER_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trips/UOM.
        /// </summary>
        public static string FREIGHT_CONTAINER {
            get {
                return ResourceManager.GetString("FREIGHT_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Cost.
        /// </summary>
        public static string FREIGHT_COST {
            get {
                return ResourceManager.GetString("FREIGHT_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Cost Per.
        /// </summary>
        public static string FREIGHT_COST_PER {
            get {
                return ResourceManager.GetString("FREIGHT_COST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Freight Cost.
        /// </summary>
        public static string FREIGHT_COST_SELECTED {
            get {
                return ResourceManager.GetString("FREIGHT_COST_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Freight Cost.
        /// </summary>
        public static string FREIGHT_COST_SUGGESTED {
            get {
                return ResourceManager.GetString("FREIGHT_COST_SUGGESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Cost UOM.
        /// </summary>
        public static string FREIGHT_COST_UOM {
            get {
                return ResourceManager.GetString("FREIGHT_COST_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Per UOM.
        /// </summary>
        public static string FREIGHT_DIFFERENT_PER_UOM {
            get {
                return ResourceManager.GetString("FREIGHT_DIFFERENT_PER_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Different.
        /// </summary>
        public static string FREIGHT_DIFFERENT_PERCENTAGE {
            get {
                return ResourceManager.GetString("FREIGHT_DIFFERENT_PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP/KG (Based Qty).
        /// </summary>
        public static string FREIGHT_KG {
            get {
                return ResourceManager.GetString("FREIGHT_KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP/KG (Based Capacity).
        /// </summary>
        public static string FREIGHT_KG_BASED {
            get {
                return ResourceManager.GetString("FREIGHT_KG_BASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight (Master Data).
        /// </summary>
        public static string FREIGHT_MASTER {
            get {
                return ResourceManager.GetString("FREIGHT_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Total Biaya Pengiriman.
        /// </summary>
        public static string FREIGHT_TOTAL_COST {
            get {
                return ResourceManager.GetString("FREIGHT_TOTAL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Biaya Pengiriman.
        /// </summary>
        public static string FREIGHT_TOTAL_COST_USER {
            get {
                return ResourceManager.GetString("FREIGHT_TOTAL_COST_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Different.
        /// </summary>
        public static string FREIGHT_TOTAL_DIFFERENT {
            get {
                return ResourceManager.GetString("FREIGHT_TOTAL_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR.
        /// </summary>
        public static string GENERATE_QR {
            get {
                return ResourceManager.GetString("GENERATE_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string IN_PROGRESS {
            get {
                return ResourceManager.GetString("IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoterm.
        /// </summary>
        public static string INCOTERM {
            get {
                return ResourceManager.GetString("INCOTERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoterm2.
        /// </summary>
        public static string INCOTERM2 {
            get {
                return ResourceManager.GetString("INCOTERM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No.
        /// </summary>
        public static string ITEM_NO {
            get {
                return ResourceManager.GetString("ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. SIM.
        /// </summary>
        public static string LICENSE_NO {
            get {
                return ResourceManager.GetString("LICENSE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN DO 3rdParty.
        /// </summary>
        public static string LN_DO_THIRD_PARTY {
            get {
                return ResourceManager.GetString("LN_DO_THIRD_PARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN SO Item No.
        /// </summary>
        public static string LN_SO_ITEM_NO {
            get {
                return ResourceManager.GetString("LN_SO_ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN SO No.
        /// </summary>
        public static string LN_SO_NO {
            get {
                return ResourceManager.GetString("LN_SO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN STO Item No.
        /// </summary>
        public static string LN_STO_ITEM_NO {
            get {
                return ResourceManager.GetString("LN_STO_ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN STO No.
        /// </summary>
        public static string LN_STO_NO {
            get {
                return ResourceManager.GetString("LN_STO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Flag.
        /// </summary>
        public static string LOCK_FLAG {
            get {
                return ResourceManager.GetString("LOCK_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Order.
        /// </summary>
        public static string MANUAL_ORDER {
            get {
                return ResourceManager.GetString("MANUAL_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Order SAP No.
        /// </summary>
        public static string MANUAL_ORDER_SAP_NO {
            get {
                return ResourceManager.GetString("MANUAL_ORDER_SAP_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Complete.
        /// </summary>
        public static string MARK_COMPLETE {
            get {
                return ResourceManager.GetString("MARK_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Complete Qty.
        /// </summary>
        public static string MARK_COMPLETE_QTY {
            get {
                return ResourceManager.GetString("MARK_COMPLETE_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string MATERIAL {
            get {
                return ResourceManager.GetString("MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Name.
        /// </summary>
        public static string MATERIAL_NAME {
            get {
                return ResourceManager.GetString("MATERIAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Qty.
        /// </summary>
        public static string MAX_QTY {
            get {
                return ResourceManager.GetString("MAX_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string MERGE {
            get {
                return ResourceManager.GetString("MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Order.
        /// </summary>
        public static string MERGE_ORDER {
            get {
                return ResourceManager.GetString("MERGE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trips.
        /// </summary>
        public static string NUM_TRIP {
            get {
                return ResourceManager.GetString("NUM_TRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trips/UOM.
        /// </summary>
        public static string NUMBER_OF_TRIP {
            get {
                return ResourceManager.GetString("NUMBER_OF_TRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Item No.
        /// </summary>
        public static string ORDER_ITEM_NO {
            get {
                return ResourceManager.GetString("ORDER_ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        public static string ORDER_NO {
            get {
                return ResourceManager.GetString("ORDER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal Berlaku Order/Shipment.
        /// </summary>
        public static string ORDER_SHIPMENT_VALID_DATE {
            get {
                return ResourceManager.GetString("ORDER_SHIPMENT_VALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string ORDER_TYPE {
            get {
                return ResourceManager.GetString("ORDER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding.
        /// </summary>
        public static string OUTSTANDING {
            get {
                return ResourceManager.GetString("OUTSTANDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding Qty.
        /// </summary>
        public static string OUTSTANDING_QTY {
            get {
                return ResourceManager.GetString("OUTSTANDING_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Day.
        /// </summary>
        public static string PER_DAY {
            get {
                return ResourceManager.GetString("PER DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Month.
        /// </summary>
        public static string PER_MONTH {
            get {
                return ResourceManager.GetString("PER MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string PLANT {
            get {
                return ResourceManager.GetString("PLANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Interco.
        /// </summary>
        public static string PO_INTERCO {
            get {
                return ResourceManager.GetString("PO_INTERCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO No.
        /// </summary>
        public static string PO_NO {
            get {
                return ResourceManager.GetString("PO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO SO.
        /// </summary>
        public static string PO_SO_NO {
            get {
                return ResourceManager.GetString("PO_SO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ePOD.
        /// </summary>
        public static string POD {
            get {
                return ResourceManager.GetString("POD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string POD_CATEGORY {
            get {
                return ResourceManager.GetString("POD_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD Qty.
        /// </summary>
        public static string POD_QTY {
            get {
                return ResourceManager.GetString("POD_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string POD_REMARKS {
            get {
                return ResourceManager.GetString("POD_REMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Qty.
        /// </summary>
        public static string POD_RETURN_QTY {
            get {
                return ResourceManager.GetString("POD_RETURN_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Delivery.
        /// </summary>
        public static string POD_TITLE {
            get {
                return ResourceManager.GetString("POD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Status.
        /// </summary>
        public static string PROGRESS_STATUS {
            get {
                return ResourceManager.GetString("PROGRESS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pur. Organization.
        /// </summary>
        public static string PUR_ORG {
            get {
                return ResourceManager.GetString("PUR_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pur / Sales Org..
        /// </summary>
        public static string PUR_SALES_ORG {
            get {
                return ResourceManager.GetString("PUR_SALES_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Order.
        /// </summary>
        public static string QTY_ORDER {
            get {
                return ResourceManager.GetString("QTY_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Shipment.
        /// </summary>
        public static string QTY_SHIPMENT {
            get {
                return ResourceManager.GetString("QTY_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realization Qty.
        /// </summary>
        public static string REAL_QTY {
            get {
                return ResourceManager.GetString("REAL_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string REASON {
            get {
                return ResourceManager.GetString("REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Qty.
        /// </summary>
        public static string RECEIVE_QTY {
            get {
                return ResourceManager.GetString("RECEIVE_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive UOM.
        /// </summary>
        public static string RECEIVE_UOM {
            get {
                return ResourceManager.GetString("RECEIVE_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal Registrasi.
        /// </summary>
        public static string REGISTRATION_DATE {
            get {
                return ResourceManager.GetString("REGISTRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Order.
        /// </summary>
        public static string REJECT_ORDER {
            get {
                return ResourceManager.GetString("REJECT_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string REJECTED {
            get {
                return ResourceManager.GetString("REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Slot.
        /// </summary>
        public static string REMAINING_SLOT {
            get {
                return ResourceManager.GetString("REMAINING_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string REMARKS {
            get {
                return ResourceManager.GetString("REMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string REPORT_DATE {
            get {
                return ResourceManager.GetString("REPORT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Date.
        /// </summary>
        public static string REPORT_GENERATE_DATE {
            get {
                return ResourceManager.GetString("REPORT_GENERATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string RETURN_SHIPMENT {
            get {
                return ResourceManager.GetString("RETURN_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Qty.
        /// </summary>
        public static string REVERT_QTY {
            get {
                return ResourceManager.GetString("REVERT_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Organization.
        /// </summary>
        public static string SALES_ORG {
            get {
                return ResourceManager.GetString("SALES_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Item No..
        /// </summary>
        public static string SAP_ITEM_NO {
            get {
                return ResourceManager.GetString("SAP_ITEM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Order No.
        /// </summary>
        public static string SAP_NO {
            get {
                return ResourceManager.GetString("SAP_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shipment.
        /// </summary>
        public static string SELECT_SHIPMENT {
            get {
                return ResourceManager.GetString("SELECT_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Transporter.
        /// </summary>
        public static string SELECT_TRANSPORTER {
            get {
                return ResourceManager.GetString("SELECT_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        public static string SHIPMENT {
            get {
                return ResourceManager.GetString("SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment No.
        /// </summary>
        public static string SHIPMENT_NO {
            get {
                return ResourceManager.GetString("SHIPMENT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Type.
        /// </summary>
        public static string SHIPMENT_TYPE {
            get {
                return ResourceManager.GetString("SHIPMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Driver Tracking.
        /// </summary>
        public static string SHOW_DRIVER_TRACKING {
            get {
                return ResourceManager.GetString("SHOW_DRIVER_TRACKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Status History.
        /// </summary>
        public static string SHOW_STATUS_HISTORY {
            get {
                return ResourceManager.GetString("SHOW_STATUS_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Name.
        /// </summary>
        public static string SLOT_NAME {
            get {
                return ResourceManager.GetString("SLOT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO of DO No.
        /// </summary>
        public static string SO_DO_NO {
            get {
                return ResourceManager.GetString("SO_DO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO Interco.
        /// </summary>
        public static string SO_INTERCO {
            get {
                return ResourceManager.GetString("SO_INTERCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO Interco Item.
        /// </summary>
        public static string SO_INTERCO_ITEM {
            get {
                return ResourceManager.GetString("SO_INTERCO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuffing Date.
        /// </summary>
        public static string STUFFING_DATE {
            get {
                return ResourceManager.GetString("STUFFING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Trips Based Capacity.
        /// </summary>
        public static string SYSTEM_NOT {
            get {
                return ResourceManager.GetString("SYSTEM_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time End.
        /// </summary>
        public static string TIME_END {
            get {
                return ResourceManager.GetString("TIME_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Start.
        /// </summary>
        public static string TIME_START {
            get {
                return ResourceManager.GetString("TIME_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        public static string TOLERANCE {
            get {
                return ResourceManager.GetString("TOLERANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Type.
        /// </summary>
        public static string TRANSFER_TYPE {
            get {
                return ResourceManager.GetString("TRANSFER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter.
        /// </summary>
        public static string TRANSPORTER {
            get {
                return ResourceManager.GetString("TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter Accept Status.
        /// </summary>
        public static string TRANSPORTER_ACCEPT_STATUS {
            get {
                return ResourceManager.GetString("TRANSPORTER_ACCEPT_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes to Transporter.
        /// </summary>
        public static string TRANSPORTER_NOTES {
            get {
                return ResourceManager.GetString("TRANSPORTER_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string TRUCK {
            get {
                return ResourceManager.GetString("TRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapasitas.
        /// </summary>
        public static string TRUCK_CAPACITY {
            get {
                return ResourceManager.GetString("TRUCK_CAPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Type.
        /// </summary>
        public static string TRUCK_TYPE {
            get {
                return ResourceManager.GetString("TRUCK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned Transporter.
        /// </summary>
        public static string UNASSIGNED_TRANSPORTER {
            get {
                return ResourceManager.GetString("UNASSIGNED_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmark Complete.
        /// </summary>
        public static string UNMARK_COMPLETE {
            get {
                return ResourceManager.GetString("UNMARK_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file(s).
        /// </summary>
        public static string UPLOAD_FILE {
            get {
                return ResourceManager.GetString("UPLOAD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Trips by User.
        /// </summary>
        public static string USER_NOT {
            get {
                return ResourceManager.GetString("USER_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string VALID_FROM {
            get {
                return ResourceManager.GetString("VALID_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string VALID_TO {
            get {
                return ResourceManager.GetString("VALID_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string VEHICLE {
            get {
                return ResourceManager.GetString("VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string VENDOR {
            get {
                return ResourceManager.GetString("VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Order.
        /// </summary>
        public static string VIEW_ORDER {
            get {
                return ResourceManager.GetString("VIEW_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View POD.
        /// </summary>
        public static string VIEW_POD {
            get {
                return ResourceManager.GetString("VIEW_POD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Realization.
        /// </summary>
        public static string VIEW_SHIPMENT_REAL {
            get {
                return ResourceManager.GetString("VIEW_SHIPMENT_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Shipments.
        /// </summary>
        public static string VIEW_SHIPMENTS {
            get {
                return ResourceManager.GetString("VIEW_SHIPMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Approval.
        /// </summary>
        public static string WAITING_FOR_APPROVAL {
            get {
                return ResourceManager.GetString("WAITING_FOR_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string WAREHOUSE {
            get {
                return ResourceManager.GetString("WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Location.
        /// </summary>
        public static string WAREHOUSE_LOCATION {
            get {
                return ResourceManager.GetString("WAREHOUSE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WB Trans Type.
        /// </summary>
        public static string WB_TRANS_TYPE {
            get {
                return ResourceManager.GetString("WB_TRANS_TYPE", resourceCulture);
            }
        }
    }
}
