//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBaseVue_Models.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to approve an expired appointment.
        /// </summary>
        public static string APPOINTMENT_APPROVAL_EXPIRED {
            get {
                return ResourceManager.GetString("APPOINTMENT_APPROVAL_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date is required.
        /// </summary>
        public static string APPOINTMENT_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("APPOINTMENT_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment slot is required.
        /// </summary>
        public static string APPOINTMENT_SLOT_REQUIRED {
            get {
                return ResourceManager.GetString("APPOINTMENT_SLOT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment for Shipment {0} successfully created.  Waiting for approval to continue..
        /// </summary>
        public static string APPOINTMENT_SUCCESS {
            get {
                return ResourceManager.GetString("APPOINTMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents for this approval not found.
        /// </summary>
        public static string APPROVAL_DOC_INVALID {
            get {
                return ResourceManager.GetString("APPROVAL_DOC_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval data not found.
        /// </summary>
        public static string APPROVAL_INVALID {
            get {
                return ResourceManager.GetString("APPROVAL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval level not found.
        /// </summary>
        public static string APPROVAL_LEVEL_INVALID {
            get {
                return ResourceManager.GetString("APPROVAL_LEVEL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next approval level not found.
        /// </summary>
        public static string APPROVAL_NEXT_INVALID {
            get {
                return ResourceManager.GetString("APPROVAL_NEXT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver is not allowed to access this application.
        /// </summary>
        public static string APPROVAL_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("APPROVAL_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has been {0} by {1} on {2} .
        /// </summary>
        public static string APPROVAL_PROCESSED {
            get {
                return ResourceManager.GetString("APPROVAL_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Orders has been assigned to customer(s)/vendor(s) {0} with new Order No. {1}.
        /// </summary>
        public static string ASSIGN_CUSTOMER_VENDOR_SUCCESS {
            get {
                return ResourceManager.GetString("ASSIGN_CUSTOMER_VENDOR_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stuffing date format.
        /// </summary>
        public static string ASSIGN_DATE_INVALID {
            get {
                return ResourceManager.GetString("ASSIGN_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional reason is required.
        /// </summary>
        public static string ASSIGN_REASON_OTHERS_REQUIRED {
            get {
                return ResourceManager.GetString("ASSIGN_REASON_OTHERS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required.
        /// </summary>
        public static string ASSIGN_REASON_REQUIRED {
            get {
                return ResourceManager.GetString("ASSIGN_REASON_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Orders has been assigned to transporter(s) {0} with new Order No. {1}.
        /// </summary>
        public static string ASSIGN_TRANSPORTER_SUCCESS {
            get {
                return ResourceManager.GetString("ASSIGN_TRANSPORTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Business Segment.
        /// </summary>
        public static string BUSINESS_SEGMENT_INVALID {
            get {
                return ResourceManager.GetString("BUSINESS_SEGMENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category is required.
        /// </summary>
        public static string BUSINESS_SEGMENT_REQUIRED {
            get {
                return ResourceManager.GetString("BUSINESS_SEGMENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change your password on first login.
        /// </summary>
        public static string CHANGE_PASSWORD_FIRST_LOGIN {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_FIRST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed. Please continue to login with new password.
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESS_LOGIN {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Company.
        /// </summary>
        public static string COMPANY_INVALID {
            get {
                return ResourceManager.GetString("COMPANY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is required.
        /// </summary>
        public static string COMPANY_REQUIRED {
            get {
                return ResourceManager.GetString("COMPANY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password does not match New Password.
        /// </summary>
        public static string CONFIRM_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required.
        /// </summary>
        public static string CONFIRM_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password is required.
        /// </summary>
        public static string CURRENT_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Customer.
        /// </summary>
        public static string CUSTOMER_INVALID {
            get {
                return ResourceManager.GetString("CUSTOMER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required.
        /// </summary>
        public static string CUSTOMER_REQUIRED {
            get {
                return ResourceManager.GetString("CUSTOMER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or incomplete data.
        /// </summary>
        public static string DATA_INVALID {
            get {
                return ResourceManager.GetString("DATA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Department.
        /// </summary>
        public static string DEPARTMENT_INVALID {
            get {
                return ResourceManager.GetString("DEPARTMENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is required.
        /// </summary>
        public static string DEPARTMENT_REQUIRED {
            get {
                return ResourceManager.GetString("DEPARTMENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Destination.
        /// </summary>
        public static string DESTINATION_INVALID {
            get {
                return ResourceManager.GetString("DESTINATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination is required.
        /// </summary>
        public static string DESTINATION_REQUIRED {
            get {
                return ResourceManager.GetString("DESTINATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Port is required.
        /// </summary>
        public static string DISCHARGE_PORT_REQUIRED {
            get {
                return ResourceManager.GetString("DISCHARGE_PORT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Distribution.
        /// </summary>
        public static string DISTRIBUTION_INVALID {
            get {
                return ResourceManager.GetString("DISTRIBUTION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution is required.
        /// </summary>
        public static string DISTRIBUTION_REQUIRED {
            get {
                return ResourceManager.GetString("DISTRIBUTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date is required.
        /// </summary>
        public static string DOC_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("DOC_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Document Type.
        /// </summary>
        public static string DOCUMENT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("DOCUMENT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this driver?.
        /// </summary>
        public static string DRIVER_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("DRIVER_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Driver.
        /// </summary>
        public static string DRIVER_INVALID {
            get {
                return ResourceManager.GetString("DRIVER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver {0} is in use in other Shipment and not available at the moment.
        /// </summary>
        public static string DRIVER_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("DRIVER_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver is required.
        /// </summary>
        public static string DRIVER_REQUIRED {
            get {
                return ResourceManager.GetString("DRIVER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one set of driver and truck is required.
        /// </summary>
        public static string DRIVER_TRUCK_REQUIRED {
            get {
                return ResourceManager.GetString("DRIVER_TRUCK_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} ORDER MANUAL - {0}.
        /// </summary>
        public static string EMAIL_SUBJECT_APPROVE_ORDER_MANUAL {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_APPROVE_ORDER_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {1} - {0}.
        /// </summary>
        public static string EMAIL_SUBJECT_APPROVED_ASSIGN_TRANSPORTER {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_APPROVED_ASSIGN_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} APPPOINTMENT - {0}.
        /// </summary>
        public static string EMAIL_SUBJECT_APPROVED_CREATE_APPOINTMENT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_APPROVED_CREATE_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO REJECT ORDER - {0}.
        /// </summary>
        public static string EMAIL_SUBJECT_AUTO_REJECT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_AUTO_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is required.
        /// </summary>
        public static string FREIGHT_CONTAINER_REQUIRED {
            get {
                return ResourceManager.GetString("FREIGHT_CONTAINER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Cost is required.
        /// </summary>
        public static string FREIGHT_COST_REQUIRED {
            get {
                return ResourceManager.GetString("FREIGHT_COST_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Group.
        /// </summary>
        public static string GROUP_INVALID {
            get {
                return ResourceManager.GetString("GROUP_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Incoterm.
        /// </summary>
        public static string INCOTERM_INVALID {
            get {
                return ResourceManager.GetString("INCOTERM_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: Unable to connect to application endpoint. Please contact administrator.
        /// </summary>
        public static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No {0} must not exceed outstanding quantity ({1}).
        /// </summary>
        public static string ITEM_EXCEED_OUTSTANDING {
            get {
                return ResourceManager.GetString("ITEM_EXCEED_OUTSTANDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License No. is required.
        /// </summary>
        public static string LICENSE_REQUIRED {
            get {
                return ResourceManager.GetString("LICENSE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Loading.
        /// </summary>
        public static string LOADING_INVALID {
            get {
                return ResourceManager.GetString("LOADING_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading is required.
        /// </summary>
        public static string LOADING_REQUIRED {
            get {
                return ResourceManager.GetString("LOADING_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Location.
        /// </summary>
        public static string LOCATION_INVALID {
            get {
                return ResourceManager.GetString("LOCATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required.
        /// </summary>
        public static string LOCATION_REQUIRED {
            get {
                return ResourceManager.GetString("LOCATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate Manual Order No..
        /// </summary>
        public static string MANUAL_ORDER_GENERATE_INVALID {
            get {
                return ResourceManager.GetString("MANUAL_ORDER_GENERATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Material {0}.
        /// </summary>
        public static string MATERIAL_INVALID {
            get {
                return ResourceManager.GetString("MATERIAL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material data is required.
        /// </summary>
        public static string MATERIAL_REQUIRED {
            get {
                return ResourceManager.GetString("MATERIAL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Matrix has been saved successfully.
        /// </summary>
        public static string MD_APPROVAL_MATRIX_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_APPROVAL_MATRIX_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Matrix for factory {0} has been saved successfully.
        /// </summary>
        public static string MD_APPT_MATRIX_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_APPT_MATRIX_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} has been saved successfully.
        /// </summary>
        public static string MD_CUSTOMER_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_CUSTOMER_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deparment {0} has been saved successfully.
        /// </summary>
        public static string MD_DEPARTMENT_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_DEPARTMENT_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Category {0} has been saved successfully.
        /// </summary>
        public static string MD_DOCUMENT_CATEGORY_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_DOCUMENT_CATEGORY_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory {0} has been saved successfully.
        /// </summary>
        public static string MD_FACTORY_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_FACTORY_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Cost for {0} has been saved successfully.
        /// </summary>
        public static string MD_FREIGHT_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_FREIGHT_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} has been saved successfully.
        /// </summary>
        public static string MD_GROUP_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_GROUP_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoterm {0} has been saved successfully.
        /// </summary>
        public static string MD_INCOTERM_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_INCOTERM_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} has been saved successfully.
        /// </summary>
        public static string MD_LOCATION_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_LOCATION_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup {0} has been saved successfully.
        /// </summary>
        public static string MD_LOOKUP_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_LOOKUP_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material {0} has been saved successfully.
        /// </summary>
        public static string MD_MATERIAL_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_MATERIAL_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Type {0} has been saved successfully.
        /// </summary>
        public static string MD_PACKING_TYPE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_PACKING_TYPE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Organization {0} has been saved successfully.
        /// </summary>
        public static string MD_PURCHASE_ORG_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_PURCHASE_ORG_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location {0} has been saved successfully.
        /// </summary>
        public static string MD_STORAGE_LOCATION_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_STORAGE_LOCATION_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has been saved successfully.
        /// </summary>
        public static string MD_USER_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_USER_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor {0} has been saved successfully.
        /// </summary>
        public static string MD_VENDOR_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MD_VENDOR_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Menu.
        /// </summary>
        public static string MENU_INVALID {
            get {
                return ResourceManager.GetString("MENU_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is required.
        /// </summary>
        public static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trips/UOM Required.
        /// </summary>
        public static string NUMBER_OF_TRIP_REQUIRED {
            get {
                return ResourceManager.GetString("NUMBER_OF_TRIP_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not allowed to be added to this Shipment.
        /// </summary>
        public static string ORDER_ADD_SHIPMENT_DENIED {
            get {
                return ResourceManager.GetString("ORDER_ADD_SHIPMENT_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {1}, Item {2} is already added to Shipment {0}. Please edit the shipment instead of adding the Order..
        /// </summary>
        public static string ORDER_ADD_SHIPMENT_EXISTED {
            get {
                return ResourceManager.GetString("ORDER_ADD_SHIPMENT_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be the same to add Order to Shipment.
        /// </summary>
        public static string ORDER_ADD_SHIPMENT_INVALID {
            get {
                return ResourceManager.GetString("ORDER_ADD_SHIPMENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been added to Shipment {1}.
        /// </summary>
        public static string ORDER_ADD_SHIPMENT_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_ADD_SHIPMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please unlock this Shipment No. in WB Application.
        /// </summary>
        public static string ORDER_ADD_SHIPMENT_UNLOCK {
            get {
                return ResourceManager.GetString("ORDER_ADD_SHIPMENT_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign driver without Qty for Order {0}.
        /// </summary>
        public static string ORDER_ASSIGN_DRIVER_QTY {
            get {
                return ResourceManager.GetString("ORDER_ASSIGN_DRIVER_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been successfully assigned to driver. Please proceed to Shipment {1} to continue..
        /// </summary>
        public static string ORDER_ASSIGN_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_ASSIGN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been cancelled successfully..
        /// </summary>
        public static string ORDER_CANCEL_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_CANCEL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to {0} order {1}?.
        /// </summary>
        public static string ORDER_CONFIRMATION {
            get {
                return ResourceManager.GetString("ORDER_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been successfully copied to Order {1}.
        /// </summary>
        public static string ORDER_COPY_COLLECTIVE_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_COPY_COLLECTIVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} cannot be copied as the status is COMPLETED.
        /// </summary>
        public static string ORDER_COPY_COMPLETED {
            get {
                return ResourceManager.GetString("ORDER_COPY_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order materials/details.
        /// </summary>
        public static string ORDER_DETAIL_INVALID {
            get {
                return ResourceManager.GetString("ORDER_DETAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been successfully rejected. Waiting for approval to continue..
        /// </summary>
        public static string ORDER_DISPATCH_REJECT_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_DISPATCH_REJECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been {1}.
        /// </summary>
        public static string ORDER_DISPATCH_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_DISPATCH_STATUS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been successfully assigned to transporter {1}.  Waiting for approval to continue..
        /// </summary>
        public static string ORDER_DISPATCH_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_DISPATCH_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been assigned to transporter {1}. Waiting for approval to assign to transporter..
        /// </summary>
        public static string ORDER_DISPATCH_WAITING {
            get {
                return ResourceManager.GetString("ORDER_DISPATCH_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}: Unable to Edit Order Qty. Qty already assigned to Shipment.
        /// </summary>
        public static string ORDER_EDIT_QTY_EXCEED {
            get {
                return ResourceManager.GetString("ORDER_EDIT_QTY_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}: Unable to edit Qty exceed O/S SAP Qty.
        /// </summary>
        public static string ORDER_EDIT_QTY_EXCEED_SAP {
            get {
                return ResourceManager.GetString("ORDER_EDIT_QTY_EXCEED_SAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}: Unable to edit Qty to zero.
        /// </summary>
        public static string ORDER_EDIT_QTY_ZERO {
            get {
                return ResourceManager.GetString("ORDER_EDIT_QTY_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete order with shipment/realization.
        /// </summary>
        public static string ORDER_EDIT_REALIZATION {
            get {
                return ResourceManager.GetString("ORDER_EDIT_REALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has been edited successfully.
        /// </summary>
        public static string ORDER_EDIT_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_EDIT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has at least one ongoing Shipment..
        /// </summary>
        public static string ORDER_HAS_ONGOING_SHIPMENT {
            get {
                return ResourceManager.GetString("ORDER_HAS_ONGOING_SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Order.
        /// </summary>
        public static string ORDER_INVALID {
            get {
                return ResourceManager.GetString("ORDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been marked as COMPLETED..
        /// </summary>
        public static string ORDER_MARK_COMPLETE_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_MARK_COMPLETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same company..
        /// </summary>
        public static string ORDER_MERGE_COMPANY {
            get {
                return ResourceManager.GetString("ORDER_MERGE_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders..
        /// </summary>
        public static string ORDER_MERGE_COUNT {
            get {
                return ResourceManager.GetString("ORDER_MERGE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same loading location.
        /// </summary>
        public static string ORDER_MERGE_LOCATION_FROM {
            get {
                return ResourceManager.GetString("ORDER_MERGE_LOCATION_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same destination location.
        /// </summary>
        public static string ORDER_MERGE_LOCATION_TO {
            get {
                return ResourceManager.GetString("ORDER_MERGE_LOCATION_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same order type.
        /// </summary>
        public static string ORDER_MERGE_ORDER_TYPE {
            get {
                return ResourceManager.GetString("ORDER_MERGE_ORDER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to merge Order {0}, SAP No {1}. Qty is required to merge..
        /// </summary>
        public static string ORDER_MERGE_QTY_INVALID {
            get {
                return ResourceManager.GetString("ORDER_MERGE_QTY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same shipment type..
        /// </summary>
        public static string ORDER_MERGE_SHIPMENT_TYPE {
            get {
                return ResourceManager.GetString("ORDER_MERGE_SHIPMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been merged as Shipment {1}.
        /// </summary>
        public static string ORDER_MERGE_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_MERGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same transporter dispatched..
        /// </summary>
        public static string ORDER_MERGE_TRANSPORTER {
            get {
                return ResourceManager.GetString("ORDER_MERGE_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requires 2(two) or more orders with the same truck type..
        /// </summary>
        public static string ORDER_MERGE_TRUCK_TYPE {
            get {
                return ResourceManager.GetString("ORDER_MERGE_TRUCK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} has been merged/deleted on {1}.
        /// </summary>
        public static string ORDER_MERGED {
            get {
                return ResourceManager.GetString("ORDER_MERGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate Order No..
        /// </summary>
        public static string ORDER_NO_GENERATE_INVALID {
            get {
                return ResourceManager.GetString("ORDER_NO_GENERATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No. {0} has not been dispatched to transporter yet..
        /// </summary>
        public static string ORDER_NO_TRANSPORTER {
            get {
                return ResourceManager.GetString("ORDER_NO_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} is on approval to be rejected.
        /// </summary>
        public static string ORDER_PENDING_REJECT {
            get {
                return ResourceManager.GetString("ORDER_PENDING_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file is required to complete Proof of Delivery.
        /// </summary>
        public static string ORDER_POD_FILES {
            get {
                return ResourceManager.GetString("ORDER_POD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD data not found.
        /// </summary>
        public static string ORDER_POD_INVALID {
            get {
                return ResourceManager.GetString("ORDER_POD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Delivery of Shipment {0} has been successfully saved..
        /// </summary>
        public static string ORDER_POD_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_POD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must be dispatched to transporter and approved.
        /// </summary>
        public static string ORDER_REQUIRE_DISPATCH {
            get {
                return ResourceManager.GetString("ORDER_REQUIRE_DISPATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order must be dispatched and accepted by the transporter.
        /// </summary>
        public static string ORDER_REQUIRE_DISPATCH_ACCEPTED {
            get {
                return ResourceManager.GetString("ORDER_REQUIRE_DISPATCH_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {1} has been splitted. New order number {0}.
        /// </summary>
        public static string ORDER_SPLIT_SUCESS {
            get {
                return ResourceManager.GetString("ORDER_SPLIT_SUCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Order Type.
        /// </summary>
        public static string ORDER_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ORDER_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} sudah tidak ditandai sebagai SELESAI..
        /// </summary>
        public static string ORDER_UNMARK_COMPLETE_SUCCESS {
            get {
                return ResourceManager.GetString("ORDER_UNMARK_COMPLETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Plant.
        /// </summary>
        public static string PLANT_INVALID {
            get {
                return ResourceManager.GetString("PLANT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number Invalid.
        /// </summary>
        public static string PLATE_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("PLATE_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted POD Category.
        /// </summary>
        public static string POD_CATEGORY_INVALID {
            get {
                return ResourceManager.GetString("POD_CATEGORY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required.
        /// </summary>
        public static string POD_CATEGORY_REQUIRED {
            get {
                return ResourceManager.GetString("POD_CATEGORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is not a picture. Only pictures are allowed to be uploaded..
        /// </summary>
        public static string POD_FILE_EXT {
            get {
                return ResourceManager.GetString("POD_FILE_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD Qty should be less than Shipment Qty [Material {0}].
        /// </summary>
        public static string POD_MATERIAL_EXCEED {
            get {
                return ResourceManager.GetString("POD_MATERIAL_EXCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Purchase Organization.
        /// </summary>
        public static string PUR_ORG_INVALID {
            get {
                return ResourceManager.GetString("PUR_ORG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Organization is required.
        /// </summary>
        public static string PUR_ORG_REQUIRED {
            get {
                return ResourceManager.GetString("PUR_ORG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks is required.
        /// </summary>
        public static string REMARKS_REQUIRED {
            get {
                return ResourceManager.GetString("REMARKS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Sales Organization.
        /// </summary>
        public static string SALES_ORG_INVALID {
            get {
                return ResourceManager.GetString("SALES_ORG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Organization is required.
        /// </summary>
        public static string SALES_ORG_REQUIRED {
            get {
                return ResourceManager.GetString("SALES_ORG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data filtered.
        /// </summary>
        public static string SAP_FILTER_EMPTY {
            get {
                return ResourceManager.GetString("SAP_FILTER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Parent Storage Location .
        /// </summary>
        public static string STORAGE_LOCATION_PARENT_INVALID {
            get {
                return ResourceManager.GetString("STORAGE_LOCATION_PARENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Type is required.
        /// </summary>
        public static string TRANSFER_REQUIRED {
            get {
                return ResourceManager.GetString("TRANSFER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter {0} has already exceeded the allowed quota of {1} (Current.
        /// </summary>
        public static string TRANSPORTER_EXCEED_QUOTA {
            get {
                return ResourceManager.GetString("TRANSPORTER_EXCEED_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Transporter.
        /// </summary>
        public static string TRANSPORTER_INVALID {
            get {
                return ResourceManager.GetString("TRANSPORTER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter Notes for Collective can be filled in respective item(s).
        /// </summary>
        public static string TRANSPORTER_NOTES_COLLECTIVE {
            get {
                return ResourceManager.GetString("TRANSPORTER_NOTES_COLLECTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Delete Quota By.
        /// </summary>
        public static string TRANSPORTER_QUOTA_BY_INVALID {
            get {
                return ResourceManager.GetString("TRANSPORTER_QUOTA_BY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this truck?.
        /// </summary>
        public static string TRUCK_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("TRUCK_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Truck Type.
        /// </summary>
        public static string TRUCK_TYPE_INVALID {
            get {
                return ResourceManager.GetString("TRUCK_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Type is required.
        /// </summary>
        public static string TRUCK_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("TRUCK_TYPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized transporter detected..
        /// </summary>
        public static string UNAUTHORIZED_TRANSPORTER {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been blocked.
        /// </summary>
        public static string USER_BLOCKED {
            get {
                return ResourceManager.GetString("USER_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deactivated.
        /// </summary>
        public static string USER_DEACTIVATED {
            get {
                return ResourceManager.GetString("USER_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this user?.
        /// </summary>
        public static string USER_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("USER_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is forbidden to access this application.
        /// </summary>
        public static string USER_FORBIDDEN {
            get {
                return ResourceManager.GetString("USER_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string USER_INVALID {
            get {
                return ResourceManager.GetString("USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked. Please contact your administrator..
        /// </summary>
        public static string USER_LOCKED {
            get {
                return ResourceManager.GetString("USER_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username / Password is invalid.
        /// </summary>
        public static string USER_PASS_INVALID {
            get {
                return ResourceManager.GetString("USER_PASS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been terminated. Please contact local IT.
        /// </summary>
        public static string USER_TERMINATED {
            get {
                return ResourceManager.GetString("USER_TERMINATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        public static string USER_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("USER_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. Please check your password and try again. If you enter wrong password 3 times, your account will be locked for 15 minutes..
        /// </summary>
        public static string USER_WRONG_PASSWORD_AD {
            get {
                return ResourceManager.GetString("USER_WRONG_PASSWORD_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Truck.
        /// </summary>
        public static string VEHICLE_INVALID {
            get {
                return ResourceManager.GetString("VEHICLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck {0} is in use in other Shipment and not available at the moment.
        /// </summary>
        public static string VEHICLE_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("VEHICLE_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle is required.
        /// </summary>
        public static string VEHICLE_REQUIRED {
            get {
                return ResourceManager.GetString("VEHICLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Vendor.
        /// </summary>
        public static string VENDOR_INVALID {
            get {
                return ResourceManager.GetString("VENDOR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor is required.
        /// </summary>
        public static string VENDOR_REQUIRED {
            get {
                return ResourceManager.GetString("VENDOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or Deleted Warehouse.
        /// </summary>
        public static string WAREHOUSE_INVALID {
            get {
                return ResourceManager.GetString("WAREHOUSE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse is required.
        /// </summary>
        public static string WAREHOUSE_REQUIRED {
            get {
                return ResourceManager.GetString("WAREHOUSE_REQUIRED", resourceCulture);
            }
        }
    }
}
