//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITM_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TransactionIndex_5a12c70f_a087_44a0_b3c0_0f51ec77e478
    {
        public System.Guid Id { get; set; }
    }
}
