//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int phone { get; set; }
        public int salary { get; set; }
        public string departement { get; set; }
    }
}
