//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee
    {
        public int C_key { get; set; }
        public string Employee_code { get; set; }
        public string FC_Code { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Alamat { get; set; }
        public string DOB { get; set; }
        public string JobCode { get; set; }
        public string JobType { get; set; }
        public Nullable<bool> StatusResign { get; set; }
        public string Estate_Code { get; set; }
        public string StatusKaryawan { get; set; }
        public string estateCode_alias { get; set; }
        public string employeeFinger { get; set; }
    }
}
