//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Estate
    {
        public int Id { get; set; }
        public string RegionCode { get; set; }
        public string CompanyCode { get; set; }
        public string EstateCode { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string ProfileName { get; set; }
        public string PlantCode { get; set; }
        public string Storage { get; set; }
        public string NoophCode { get; set; }
        public Nullable<int> estateFingerCode { get; set; }
        public string templateCode { get; set; }
        public Nullable<byte> isActive { get; set; }
        public string estateAlias { get; set; }
    }
}
