//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FC
    {
        public int Id { get; set; }
        public string FCCode { get; set; }
        public string Name { get; set; }
        public string Alamat { get; set; }
        public string Email { get; set; }
        public string EstateCode { get; set; }
        public string estateCodealias { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
