//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_incidentType
    {
        public int C_key { get; set; }
        public string incidentCode { get; set; }
        public string incidentName { get; set; }
        public string incidentNameEng { get; set; }
    }
}
