//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.GroupMenu = new HashSet<GroupMenu>();
        }
    
        public long Id { get; set; }
        public string MenuName { get; set; }
        public string MenuAction { get; set; }
        public string MenuController { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupMenu> GroupMenu { get; set; }
    }
}
