//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public long Id { get; set; }
        public string ReferenceNo { get; set; }
        public string Action { get; set; }
        public string Subject { get; set; }
        public string MailTo { get; set; }
        public string MailCc { get; set; }
        public string MailBody { get; set; }
        public string Result { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
