//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public long Id { get; set; }
        public string RefNo { get; set; }
        public string LocationCode { get; set; }
        public string ActionRole { get; set; }
        public string Action { get; set; }
        public string Notes { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    }
}
