//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RunningNumber()
        {
            this.RunningNumberDate = new HashSet<RunningNumberDate>();
            this.RunningNumberMonth = new HashSet<RunningNumberMonth>();
            this.RunningNumberYear = new HashSet<RunningNumberYear>();
        }
    
        public long Id { get; set; }
        public string TransType { get; set; }
        public Nullable<int> RangeFromNumber { get; set; }
        public Nullable<int> RangeToNumber { get; set; }
        public string Format { get; set; }
        public string AdditionalTrans { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string EditedBy { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Deleted_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunningNumberDate> RunningNumberDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunningNumberMonth> RunningNumberMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunningNumberYear> RunningNumberYear { get; set; }
    }
}
