//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IncidentData
    {
        public int Id { get; set; }
        public string IncidentID { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public Nullable<System.TimeSpan> IncidentTime { get; set; }
        public string IncidentCode { get; set; }
        public string EstateCode { get; set; }
        public string Block { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Flag { get; set; }
        public string InputBy { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Close { get; set; }
        public Nullable<int> LostBunches { get; set; }
        public Nullable<int> RecoverBunches { get; set; }
        public Nullable<int> TotalThief { get; set; }
        public string Comment { get; set; }
    }
}
