//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IncidentDataDetail
    {
        public int Id { get; set; }
        public string IncidentDetailID { get; set; }
        public string IncidentID { get; set; }
        public Nullable<System.DateTime> IncidentDetailDate { get; set; }
        public Nullable<System.TimeSpan> IncidentDetailTime { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LostBunches { get; set; }
        public Nullable<int> RecoverBunches { get; set; }
        public Nullable<int> TotalThief { get; set; }
    }
}
