//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBaseVue_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public long Id { get; set; }
        public string Username { get; set; }
        public string Token { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Active { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
