const message = {
    code: "Code",
    code_sap: "Code (SAP)",
    description: "Description",
    created_date: "Created Date",
    created_by: "Created By",
    edited_date: "Edited Date",
    edited_by: "Edited By",
    is_deleted: "Deleted",
    deleted_date: "Deleted Date",
    deleted_by: "Deleted By",
    company: "Company",
    document_category: "Document Category",
    packing_type: "Packing Type",
    department: "Department",
    lookup: "Lookup",
    user:"User",
    location: "Location",
    group: "Group",
    menu: "Menu",
    username: "Username",
    password: "Password",
    create: "Create",
    clear: "Clear",
    emp_number: "Username",
    full_name: "Full Name",
    email: "Email",
    is_admin: "Is Admin",
    use_ad: "Use AD",
    all_company: "All Company",
    all_department: "All Department",
    lookup_group: "Lookup Group",
    lookup_key: "Lookup Key",
    lookup_value: "Lookup Value",
    lookup_info1: "Lookup Info1",
    lookup_info2: "Lookup Info2",
    type:"Type",
    expiry_period: "Expiry Period",
    save: "Save",
    back: "Back",
    storage_location: "Storage Location",
    parent: "Parent",
    storage_desc: "Storage Description",
    release_matrix : "Release Matrix",
    approval_as : "Approval As",

    yes: "Yes",
    no: "No",

    version: "Version",
    version_date: "Version Date",
    changelog: "Changelog",
    version_active: "Active Version",
    doc_no : "Doc. No",
    doc_desc : "Doc. Description",
    doc_cat : "Doc. Category",
    doc_vad : "Doc. Validity",
    packing : "Packing",
    period_from :"Period From",
    period_to :"Period To",
    trans_no : "Transaction No",
    packing_no : "Packing No",    
    employee_number: "Employee Number",
    inputnik: "Input Employee Number",    
    apphod : "Approved By HoD",
    apphoga: "Approved By HoGA",
    pic_name : "PIC Dept",
    comp_code : "Company Code",
    sap_cod : "Company Code (SAP)",
    account: "Account",
    vehicle: "Vehicle",
    name: "Name",
    remark: "Remark",
    uom : "UoM",
    qty: "Qty",
    total_price: "Total Price",
    validity:"Validity",
    approval : "Approval Level (fill in numbers 1 to 5)",
    Material_Code: "Material Code",
    posted: "Posted",
    item_name: "Name of Item",
    qty_receive: "Qty Received",
    price_uom: "Price per UoM",
    release_as : "Release As",
    status : "Status",
    req_stat : "Request Status",
    qty_req : "Qty Request",
    qty_rec : "Qty Receive",
    qty_dif : "Qty Difference",
    qty_Dis: "Qty Distribute",
    qty_Adj: "Qty Adjustment",    
    stock_remain: "Remaining Stock",
    dept_stock: "Dept Stock",
    dept_request: "Dept Request",
    request_no:"Request No",    
    approve: "Approve",
    reject: "Reject",
    revise: "Request for Info",
    approval_confirmation: "Approval Confirmation",
    period: "Period",    
    level: "Level",        
    info: "Info",
    dept_code: "Department Code",
    price : "Price",    
    mode: "Mode",
    material: "Material",
    isurgnt: "Is Urgent",
    note: "Note",
    noteCm: "Note or Comment",    
    desc : "Description",
    year: "Year",
    address: "Address",
    codesubasset : "Sub Asset",
    descsubasset: "Description Sub Asset",
    assetcategory: "Asset Category",
    brand:"Brand",
    active : "Active",
    color: "Color",
    plat: "Plat No",
    taxexpired: "Tax Expired",
    identity_no :"Identity No",
    lastodometer:"Last Odometer",
    supplier : "Supplier",
    repairtype : "R/M Type",
    from_date : "From Date",
    to_date : "To Date",
    notes: "Notes",
    sort_by : "Sort By",
    valid_date : "Valid Date",
    modul : "Modul",
    category : "Category",
    to_valid_date : "To Valid Date",
    kode_bpk : "BPK Code",
    tgl_bpk  : "BPK Date",
    nik : "NIK",
    nama_bagian : "Part Name",
    dibayarkan : "Payment By",
    kode_bayar : "Payment Code",
    user_manager : "User Manager",
    wilayah : "Region",
    payment : "Payment Type",   
    familyrelation: "Family Relation",
    currency: "Ccy",
    rate: "Rate", 
    amount: "Amount",
    local_amount: "Local Amount",
    odometer: "Odometer",
    fuel_type: "Fuel Type",
    fuel_consumption: "Total Liter",
    to : "To",

    gastock : "GA Stok",
    stockqty : "Departement Stok",
    cashbank: "Cash/Bank",
    drivername: "Driver Name",
    platno: "Police No",
    asset_type: "Asset Type",
    sub_asset_type: "Sub Asset Type",
    bank_name : "Bank Name",
    account_no : "Account No",
    account_name : "Account Name",
    account_type : "Account Type",

    log_history: "Changes History",
    release_approval: "Release Approval",
    is_required: "Value is required",
    reason: "Reason",

    posted_by: "Posted By",
    receive_by: "Receive By",
    req_by : "Request By",
    approved_by: "Approved By",
    charged_by: "Charged By",
    known_by: "Known By",
    recorded_by: "Recorded By",

    ref_no : "Ref No",
    pr_no: "PO No",
    item_no: "Item No",        

    price_date: "Price Date",
    doc_date: "Document Date",
    receive_date: "Receive Date",    
    posted_date: "Posted Date",
    req_date: "Request Date",
    approved_date: "Approved Date",  
    date: "Date",
    estimatedate:"Estimate Date",    
    actual_date: "Actual Date",

    View: "View",
    Create: "Create",
    Edit: "Edit",
    Delete: "Delete",
    Print: "Print",

    destroyed_after : "Destroyed After",
    doc_type : "Document Type",
    des_code : "Destination Code",
    parent_id : "Parent",
    is_storage : "Is Storage",
    new_packing : "New Packing",
    from_packing : "From Packing No.",
    to_packing : "Relocate To Packing No.",
    report_type : "Report Type",

    document_deactivation: "Document Deactivation",
    document_transfer: "Document Transfer",
    package_document: "Packing/Document",
    storage_from: "Storage From",
    batch_no: "Batch No",
    document: "Document",
    transfer_type:"Transfer Type",
    expedition:"Expedition/Courier",
    destination :"Destination",
    return_date : "Return Date",
    transaction_date : "Transaction Date",
    attachment : "Attachment",
    upload : "Upload",
    uploaddetail :"Upload Detail(s)",
    approval_by : "Approval By",
    approval_date : "Approval Date",
    matrix : "Matrix",
    document_desc:"Document Desc",
    last_approval_by : "Last Approval By",
    last_approval_date : "Last Approval Date",
    
    alert:{
        require_loading: "Loading is required",
        require_destination: "Destination is required",
        require_charge_oa_company: "Charge OA Company is required",
        require_freight_date: "Freight Date is required",
        require_stuffing_date: "Stuffing Date is required",
        require_qty_assign_driver: "Cannot assign driver without quantity",
        require_driver_assign_driver: "Driver is required",
        require_license_assign_driver: "License No. is required",
        require_vehicle_assign_driver: "Truck is required",
        require_transporter: "Transporter is required",
        require_reason: "Reason is required",
        require_name: "Name is required",
        require_license_no: "License No. is required",
        require_address: "Address is required",
        require_date_of_birth: "Date of Birth is required",
        require_shipment_no: "Shipment No. is required",
        require_driver: "At least 1(one) or more driver(s) required",
        require_slot: "Slot is required",

        
    },
    message:{
        approval_confirmation: "Are you sure? These selected document(s) will be ",
        transporter_action_confirmation_accept: "Are you sure to accept these order(s)?",
        transporter_action_confirmation_reject: "Are you sure to reject these order(s)?",
        sap_filter_authorization: "The colored rows indicates that you do not have authorization to save"
    }
}

export default message;